const data = new Date();
console.log(data.toString());
console.log(data.getDate());
console.log(data.getMonth() + 1);
console.log(data.getFullYear());
console.log(data.getHours());
console.log(data.getMinutes());
console.log(data.getSeconds());
console.log(data.getMilliseconds());
console.log(data.getDay());